name: Taura CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest pytest-cov

      - name: Lint with Ruff
        run: ruff check . --exclude notebooks/

      - name: Check formatting with Ruff
        run: ruff format --check . --exclude notebooks/

      - name: Create tests directory (if it doesn't exist)
        run: |
          mkdir -p tests

      - name: Run tests and generate coverage
        run: |
          pytest tests/ --cov=. || {
            if [[ $(pytest tests/ --collect-only | grep "collected 0 items" | wc -l) -gt 0 ]]; then
              echo "No tests found yet."
              exit 0
            else
              exit 1
            fi
          }

      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
